eventConfig:
  - name: BulletHitBreakpoint
    type: Breakpoint
    description: Bullet hit enemy
    properties:
      - name: targetEnemy
        type: Enemy
      - name: bullet
        type: Bullet
    condition: "targetEnemy.currentHealth < 10"
  - name: HealthChangeEvent
    type: Event
    description: Health changed
    properties:
      - name: previousHealth
        type: int
      - name: currentHealth
        type: int
  - name: FireBulletBreakpoint
    type: Breakpoint
    description: Player fired a bullet
    properties:
      - name: player
        type: PlayerControl
      - name: bullet
        type: Bullet
